- name: Initialize and run testing suite
  hosts: testing_vm
  become: true
  become_user: tsuite1
  vars:
    ansible_shell_executable: /bin/bash
    release_version: "5.0.13"
    base_dir: "/home/tsuite1/testing_suite_runs"
    config_file: "prod_config.yml"
  tasks:
    - name: Generate timestamp
      set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H%M%S') }}"
        cacheable: false

    - name: Set run_dir
      set_fact:
        run_dir: "{{ base_dir }}/{{ release_version }}/run_{{ timestamp }}"

    - name: Create directory for release
      file:
        path: "{{ base_dir }}/{{ release_version }}"
        state: directory

    - name: Create directory for this run
      file:
        path: "{{ run_dir }}"
        state: directory

    - name: Clean testing suite
      shell: bash -l -c "~/envs/tsuite-env/bin/testing_suite --clean --config_file {{ config_file }} > {{ run_dir }}/clean.log 2>&1"
      args:
        chdir: /home/tsuite1/testing_suite

    - name: Refresh testing suite
      shell: bash -l -c "~/envs/tsuite-env/bin/testing_suite --refresh clone --config_file {{ config_file }} > {{ run_dir }}/refresh.log 2>&1"
      args:
        chdir: /home/tsuite1/testing_suite

    - name: Create experiments
      shell: bash -l -c "~/envs/tsuite-env/bin/testing_suite --create --config_file {{ config_file }} > {{ run_dir }}/create.log 2>&1"
      args:
        chdir: /home/tsuite1/testing_suite

    - name: Run experiments
      shell: bash -l -c "nohup ~/envs/tsuite-env/bin/testing_suite --run --config_file {{ config_file }} > {{ run_dir }}/run.log 2>&1"
      args:
        chdir: /home/tsuite1/testing_suite

    - name: Wait before checking status
      pause:
        minutes: 5   # adjust depending on how long jobs take

    - name: Check experiment status
      shell: bash -l -c "~/envs/tsuite-env/bin/testing_suite --status --config_file {{ config_file }} > {{ run_dir }}/status.log 2>&1"
      args:
        chdir: /home/tsuite1/testing_suite
      register: suite_status

    - name: Show status table
      debug:
        var: suite_status.stdout
